quickstart-k8s.yaml

This will update the Kubernetes quickstart with the following changes:
- fix instructions for operator changes
- add the fallback enforcer creation here
- add the creation of an optional automation which will install default fallback policies in every namespace that gets created

Updating Kubernetes quickstart

---

quickstart-k8s.yaml

somebody will have to explain to me why this change is required for apoctl, but with the change the import in the UI doesn't work

K8S Quickstart Fix

---

quickstart-linux.yaml

This PR intends to fix multiple issues:

fix linux quickstart

---

quickstart-k8s.yaml

fix the quickstart k8s recipe file for linking with the new docs link

fix quickstart-k8s recipe

---

quickstart-linux.yaml

https://github.com/aporeto-inc/aporeto/issues/2666
Fixes for issues brought up in above ticket.
Not sure about what to do for the `You can either choose to use the current namespace https://docs.aporeto.com or create a new one.` having that https://docs.aporeto.com link there for a namespace so didn't touch that.

Fix Secure a Linux Service Recipe

---

account-organizational-metadata.yaml
create-workspace-platform-app.yaml
design-mode.yaml

- Review create workspace/platform/app recipe
- Update design mode so external networks are using servicePorts which is the latest notation

Improve recipes

---

design-mode.yaml

#Fixes  https://github.com/aporeto-inc/aporeto-devs/issues/835

icmp6-support-in-design-mode

---

cloud-auto-registration.yaml

-- MINOR bad english fixes
-- removed default value from claims field

Some minor fixes to cloud auto-registration recipe

---

policy-suggest-client-to-eks-node.yaml

Per https://redlock.atlassian.net/browse/CNS-3399, we want a new rule that allows incoming traffic into an EKS node.
> Fixes: https://redlock.atlassian.net/browse/CNS-3399

New: EKS host-mode node rule

---

TEMPLATE.yaml
cloud-auto-registration.yaml

> Fixes https://redlock.atlassian.net/browse/CNS-3463

Add successfullMessage to cloud-auto-registration.yaml

---

automations/automation-action-create-alarm.yaml
automations/automation-action-debug-params.yaml
automations/automation-action-debug-payload.yaml
automations/automation-action-enable-disable-objects.yaml
automations/automation-action-post-slack.yaml
automations/automation-condition-always-continue.yaml
automations/automation-condition-audit-violations-limit.yaml
automations/automation-condition-flows-rejected-limit.yaml
automations/automation-condition-networkpolicies-matching.yaml
automations/automation-condition-object-has-tags.yaml

We are resurrecting automation templates but in a different form. The first step is to split templates into their actions and conditions. Future work will move towards allowing a user to define an action or condition, but this first step starts us off with some defaults.

New: Automation action and condition yamls

---

policy-suggest-kube-system-to-host-pu.yaml
policy-suggest-pc-api-server-and-konnectivity.yaml
policy-suggest-pc-api-server-to-pc-console.yaml

There is a need for three new OOB rulesets to cover aggregated API server and Konnectivity (a rework from the prior one). Details are outlined in https://redlock.atlassian.net/browse/CNS-3915
> Fixes: https://redlock.atlassian.net/browse/CNS-3915

New: Three new OOB rule recipes for aggregated API server and Konnectivity

---

automations/automation-condition-flow-reports-matching-rulesets.yaml
automations/recipe-automation-ruleset-alert.yaml

These changes leverage the `.Aporeto.UI` attribute populated in https://git.scm.prismacloud.io/prismacloud/pcn/backend/-/merge_requests/1532

New: Add UI URL to ruleset workflow

---

automations/automation-condition-audit-event-content.yaml
automations/recipe-automation-audit-event.yaml

Per https://redlock.atlassian.net/browse/CNS-4134, we want a new automation that covers a few audit scenarios. The initial concept will cover choosing one or more of the below:
- Namespaces
- Network Ruleset Policies
- Application Credentials
And the customer will be able to choose to listen to the following event types:
- Create
- Update
- Delete

New: Audit Event Automation

---

automations/automation-condition-flow-reports-matching-rulesets.yaml

stringify flow data

---

policy-suggest-kube-system-to-host-pu.yaml

> Fixes https://redlock.atlassian.net/browse/CNS-4721

Add incoming @org:kubernetes=kube-system

---

policy-suggest-kube-system-to-host-pu.yaml

> Fixes: https://redlock.atlassian.net/browse/CNS-4976

move policy-suggest-kube-system-to-host-pu to group

---

automations/automation-condition-audit-event-content.yaml

> Fixes https://redlock.atlassian.net/browse/CNS-5065
As per request we're displaying only identity, eventType, id, namespace, roles and updateTime

Limit content data as per ticket

---

policy-suggest-ecs-agent.yaml

Description:
See https://redlock.atlassian.net/browse/CNS-5364

Rename OOB ECS Ruleset name from "Allow ECS Agent" -> "Allow ECS Agent Traffic"

---

automations/recipe-automation-audit-event.yaml
automations/recipe-automation-enforcer-event.yaml
automations/recipe-automation-pu-event.yaml
automations/recipe-automation-ruleset-alert.yaml
automations/recipe-automation-suspicious-communication-alert.yaml

> Fixes: https://redlock.atlassian.net/browse/CNS-5569

limit 'Name' field to 200 characters
